services:
  mysql:
    image: mysql:8.4
    container_name: lara_mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel1db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: ciscohtl
    ports:
      - "3306:3306"
    volumes:
      - ./lara_mysql_data:/var/lib/mysql